// Patternflow Dashboard - the settings page at http://patternflow.local/dashboard (dashboard.html)
//   - location: the browser looks the place up, the panel stores coordinates only
//   - night mode: sleep from / until
//   - GIFs: the browser decodes and converts them, the panel stores the clips
// Nothing personal is ever compiled into the firmware.
#pragma once
#include <Arduino.h>
#include <FFat.h>
#include "../../src/core_loop_sync.h"
#include "../../src/core_patterns_http.h"
#include "../../src/core_send.h"
#include "dash_accel.h"
#include "dash_clocks.h"
#include "dash_gifs.h"
#include "dash_state.h"
#include "dash_night.h"
#include "dash_weather.h"
#include "dashboard_index.h"  // generated by build.sh from dashboard.html

namespace DashHttp {

inline WebServer& server() { return PatternflowPatternsHttp::server(); }

inline void sendJson(int code, const String& json) {
  server().sendHeader("Cache-Control", "no-store");
  server().send(code, "application/json", json);
}

// The page is dashboard.html, stamped and gzipped by Patternflow's console tool
// (tools/console_page.py), and sent the way Patternflow sends its own pages.
inline void handlePage() { PFSend::gz(server(), DASHBOARD_INDEX_HTML_GZ, DASHBOARD_INDEX_HTML_GZ_LEN); }

inline void handleGet() {
  const bool has = DashWeather::hasLocation();
  // The clock text is JSON-safe apart from its newlines (names and labels are filtered on the way in)
  String clocksJson;
  (void)PFLoopSync::run([&] { clocksJson = DashClocks::format(); });
  clocksJson.replace("\n", "\\n");
  char head[260 + 4 * 128];
  snprintf(head, sizeof head,
           "{\"place\":\"%s\",\"lat\":%.4f,\"lon\":%.4f,\"updated\":%u,\"error\":\"%s\","
           "\"night\":{\"on\":%s,\"start\":%d,\"end\":%d},\"free\":%u,\"clocks\":\"%s\",\"gifs\":[",
           has ? DashWeather::place : "", has ? DashWeather::lat : 0.0f, has ? DashWeather::lon : 0.0f,
           DashWeather::updatedAtMs ? (unsigned)((millis() - DashWeather::updatedAtMs) / 1000) : 0u,
           DashWeather::lastError, DashNight::enabled ? "true" : "false", DashNight::startMin, DashNight::endMin,
           (unsigned)(FFat.totalBytes() - FFat.usedBytes()), clocksJson.c_str());
  String json = head;
  // The clip list belongs to the loop task: copy it there.
  String list;
  (void)PFLoopSync::run([&] {
    if (DashGifs::listDirty) DashGifs::rescan();
    for (int i = 0; i < DashGifs::count; i++) {
      if (i) list += ',';
      list += '"';
      list += DashGifs::names[i];
      list += '"';
    }
  });
  json += list;
  json += "]}";
  sendJson(200, json);
}

inline void handleLocation() {
  if (!server().hasArg("lat") || !server().hasArg("lon")) {
    sendJson(400, "{\"error\":\"lat and lon required\"}");
    return;
  }
  const float la = server().arg("lat").toFloat(), lo = server().arg("lon").toFloat();
  if (la < -90 || la > 90 || lo < -180 || lo > 180) {
    sendJson(400, "{\"error\":\"out of range\"}");
    return;
  }
  // Keep only characters the panel can draw and JSON can carry unescaped.
  const String name = server().arg("place");
  String clean;
  for (size_t i = 0; i < name.length() && clean.length() < 38; i++) {
    const char c = name[i];
    if (c >= 0x20 && c < 0x7f && c != '"' && c != '\\') clean += c;
  }
  DashWeather::saveSettings(la, lo, clean.c_str());
  DashWeather::requestFetch();
  handleGet();
}

inline void handleClocks() {
  const String text = server().arg("clocks");
  if (text.length() > 4 * 128) {
    sendJson(400, "{\"error\":\"too long\"}");
    return;
  }
  int n = 0, lines = 0;
  for (size_t i = 0; i < text.length(); i++) lines += text[i] == '\n';
  if (text.length()) lines++;
  (void)PFLoopSync::run([&] {
    n = DashClocks::parseAll(text.c_str());
    DashClocks::save();
  });
  if (n != lines && lines <= DashClocks::MAX) {
    sendJson(400, "{\"error\":\"some clocks could not be read\"}");
    return;
  }
  sendJson(200, String("{\"ok\":true,\"count\":") + n + "}");
}

inline void handleNight() {
  const int start = DashNight::parseClock(server().arg("start").c_str());
  const int end = DashNight::parseClock(server().arg("end").c_str());
  if (start < 0 || end < 0) {
    sendJson(400, "{\"error\":\"times as HH:MM\"}");
    return;
  }
  const bool on = server().arg("on") == "1";
  (void)PFLoopSync::run([&] { DashNight::save(on, start, end); });
  sendJson(200, "{\"ok\":true}");
}

// ---- GIF clip upload: streamed to a temporary file, checked, then renamed
inline File upFile;
inline bool upFailed = false;
inline char upError[48] = "";
inline uint32_t upBytes = 0;

inline void tmpPath(char* out, size_t n, char o) { snprintf(out, n, "%s/.upload.%c.tmp", DashGifs::DIR, o); }

inline void handleUpload() {
  HTTPUpload& up = server().upload();
  const String name = server().arg("name");
  const String o = server().arg("o");
  char tmp[64];
  tmpPath(tmp, sizeof tmp, o == "p" ? 'p' : 'l');
  if (up.status == UPLOAD_FILE_START) {
    upFailed = false;
    upError[0] = 0;
    upBytes = 0;
    if (!DashGifs::validName(name.c_str()) || (o != "p" && o != "l")) {
      upFailed = true;
      snprintf(upError, sizeof upError, "bad name or orientation");
      return;
    }
    if (!DashGifs::ensureDir()) {
      upFailed = true;
      snprintf(upError, sizeof upError, "cannot create %s", DashGifs::DIR);
      return;
    }
    upFile = FFat.open(tmp, FILE_WRITE);
    if (!upFile) {
      upFailed = true;
      snprintf(upError, sizeof upError, "cannot write");
    }
  } else if (up.status == UPLOAD_FILE_WRITE) {
    if (upFailed || !upFile) return;
    if (upFile.write(up.buf, up.currentSize) != up.currentSize) {
      upFailed = true;
      snprintf(upError, sizeof upError, "storage full");
    }
    upBytes += up.currentSize;
  } else if (up.status == UPLOAD_FILE_END || up.status == UPLOAD_FILE_ABORTED) {
    if (upFile) upFile.close();
    if (up.status == UPLOAD_FILE_ABORTED) {
      upFailed = true;
      snprintf(upError, sizeof upError, "upload aborted");
    }
    if (upFailed) FFat.remove(tmp);
  }
}

inline void handleUploadDone() {
  const String name = server().arg("name");
  const bool portrait = server().arg("o") == "p";
  char tmp[64], dst[64];
  tmpPath(tmp, sizeof tmp, portrait ? 'p' : 'l');
  if (upFailed) {
    sendJson(400, String("{\"error\":\"") + upError + "\"}");
    return;
  }
  // Check the header against the size before anything can play it.
  File f = FFat.open(tmp, FILE_READ);
  uint8_t head[12] = {};
  const bool read = f && f.read(head, 12) == 12;
  const uint32_t size = f ? f.size() : 0;
  if (f) f.close();
  const int w = head[4] | head[5] << 8, h = head[6] | head[7] << 8, frames = head[8] | head[9] << 8;
  const bool ok = read && memcmp(head, "DGF1", 4) == 0 && w == (portrait ? 64 : 128) && h == (portrait ? 128 : 64) &&
                  frames >= 1 && frames <= DashGifs::MAX_FRAMES && size == 12u + 2u * frames + (uint32_t)frames * w * h;
  if (!ok) {
    FFat.remove(tmp);
    sendJson(400, "{\"error\":\"not a valid clip\"}");
    return;
  }
  DashGifs::path(dst, sizeof dst, name.c_str(), portrait);
  (void)PFLoopSync::run([&] {
    if (strcmp(DashGifs::player.name, name.c_str()) == 0) DashGifs::player.stop();
    DashGifs::forget(name.c_str());
    FFat.remove(dst);
    FFat.rename(tmp, dst);
    DashGifs::listDirty = true;
  });
  Serial.printf("[DASH] gif %s (%s): %d frames\n", name.c_str(), portrait ? "portrait" : "landscape", frames);
  sendJson(200, "{\"ok\":true}");
}

inline void handleDelete() {
  const String name = server().arg("name");
  if (!DashGifs::validName(name.c_str())) {
    sendJson(400, "{\"error\":\"bad name\"}");
    return;
  }
  (void)PFLoopSync::run([&] { DashGifs::removeClip(name.c_str()); });
  sendJson(200, "{\"ok\":true}");
}

inline void handleRename() {
  const String from = server().arg("name"), to = server().arg("to");
  if (!DashGifs::validName(from.c_str()) || !DashGifs::validName(to.c_str())) {
    sendJson(400, "{\"error\":\"names: a-z, 0-9 and - only\"}");
    return;
  }
  const char* error = nullptr;
  (void)PFLoopSync::run([&] { error = DashGifs::renameClip(from.c_str(), to.c_str()); });
  if (error) {
    sendJson(400, String("{\"error\":\"") + error + "\"}");
    return;
  }
  sendJson(200, "{\"ok\":true}");
}

inline void handleOrientationGet() {
  char json[200];
  const float x = DashAccel::gx, y = DashAccel::gy, z = DashAccel::gz;
  snprintf(json, sizeof json,
           "{\"enabled\":%s,\"present\":%s,\"auto\":%s,\"flip\":%s,\"orientation\":%d,\"sensed\":%d,\"g\":[%.2f,%.2f,%.2f]}",
           DashAccel::enabled ? "true" : "false", DashAccel::present ? "true" : "false", DashAccel::autoRotate ? "true" : "false",
           DashAccel::flipPatterns ? "true" : "false", DashState::orientation,
           DashAccel::present ? DashAccel::orientationOf(x, y, z) : -1, x, y, z);
  sendJson(200, json);
}

inline void handleOrientationPost() {
  const String action = server().arg("action");
  bool ok = true;
  (void)PFLoopSync::run([&] {
    if (server().hasArg("enabled")) DashAccel::enabled = server().arg("enabled") == "1";
    if (server().hasArg("auto")) DashAccel::autoRotate = server().arg("auto") == "1";
    if (server().hasArg("flip")) DashAccel::flipPatterns = server().arg("flip") == "1";
    if (action == "upright") ok = DashAccel::calibrateUpright();
    if (action == "flipportrait") DashAccel::uprightSign = -DashAccel::uprightSign;
    if (action == "fliplandscape") DashAccel::landscapeSign = -DashAccel::landscapeSign;
    DashAccel::save();
    DashAccel::apply();
    // Apply right away instead of waiting for the next turn
    const int o = DashAccel::orientationOf(DashAccel::gx, DashAccel::gy, DashAccel::gz);
    if (DashAccel::present && DashAccel::autoRotate && o >= 0) DashState::orientation = o;
  });
  if (!ok) {
    sendJson(400, "{\"error\":\"hold the panel upright and still\"}");
    return;
  }
  handleOrientationGet();
}

inline void registerRoutes() {
  server().on("/api/dashboard/orientation", HTTP_GET, handleOrientationGet);
  server().on("/api/dashboard/orientation", HTTP_POST, handleOrientationPost);
  server().on("/dashboard", HTTP_GET, handlePage);
  server().on("/api/dashboard", HTTP_GET, handleGet);
  server().on("/api/dashboard", HTTP_POST, handleLocation);
  server().on("/api/dashboard/night", HTTP_POST, handleNight);
  server().on("/api/dashboard/clocks", HTTP_POST, handleClocks);
  server().on("/api/dashboard/gif", HTTP_POST, handleUploadDone, handleUpload);
  server().on("/api/dashboard/gif/delete", HTTP_POST, handleDelete);
  server().on("/api/dashboard/gif/rename", HTTP_POST, handleRename);
}

}  // namespace DashHttp
