#!/usr/bin/env python3
"""Turns tools/font/bold7.txt into feature/dashboard/dash_font_bold.h (an Adafruit GFXfont).

    python3 tools/font/make_font.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "tools/font/bold7.txt"
OUT = ROOT / "feature/dashboard/dash_font_bold.h"
H = 7

glyphs, name, rows = {}, None, []
for line in SRC.read_text(encoding="utf-8").split("\n"):
    if line.startswith("#") and name is None:
        continue
    if line.startswith("= "):
        if name is not None:
            glyphs[name] = rows
        name, rows = line[2:3], []
    elif name is not None and line.strip():
        rows.append(line.strip())
glyphs[name] = rows
for c, r in glyphs.items():
    assert len(r) == H and len({len(x) for x in r}) == 1, f"glyph {c!r}: {len(r)} rows, widths {[len(x) for x in r]}"
for c in "abcdefghijklmnopqrstuvwxyz":
    glyphs[c] = glyphs[c.upper()]

bitmap, table = [], []
first, last = 0x20, 0x7E
for code in range(first, last + 1):
    c = chr(code)
    r = glyphs.get(c)
    if r is None:  # not drawn: an empty advance, like a narrow space
        table.append((len(bitmap), 0, 0, 2, 0, 0, c))
        continue
    w = len(r[0])
    bits = [ch == "#" for row in r for ch in row]
    offset = len(bitmap)
    for i in range(0, len(bits), 8):
        byte = 0
        for j, b in enumerate(bits[i:i + 8]):
            byte |= b << (7 - j)
        bitmap.append(byte)
    table.append((offset, w, H, w + 1, 0, -H, c))

# The degree sign lives outside ASCII: it is drawn for '`' (unused otherwise)
deg = glyphs["°"]
w = len(deg[0])
bits = [ch == "#" for row in deg for ch in row]
off = len(bitmap)
for i in range(0, len(bits), 8):
    byte = 0
    for j, b in enumerate(bits[i:i + 8]):
        byte |= b << (7 - j)
    bitmap.append(byte)
table[ord("`") - first] = (off, w, H, w + 1, 0, -H, "`")

out = ["// GENERATED by tools/font/make_font.py from tools/font/bold7.txt: edit that.",
       "// DashBold7: 7 rows high, strokes 2 LEDs wide, drawn for this project (MIT).",
       "// '`' draws a degree sign.",
       "#pragma once", "#include <Adafruit_GFX.h>", "",
       "const uint8_t DashBold7Bitmaps[] PROGMEM = {"]
for i in range(0, len(bitmap), 16):
    out.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
out += ["};", "", "const GFXglyph DashBold7Glyphs[] PROGMEM = {"]
for off, w, h, adv, xo, yo, c in table:
    shown = c if c not in "\\'" else "\\" + c
    out.append(f"    {{{off}, {w}, {h}, {adv}, {xo}, {yo}}},  // 0x{ord(c):02X} '{shown}'")
out += ["};", "", "const GFXfont DashBold7 PROGMEM = {(uint8_t *)DashBold7Bitmaps, (GFXglyph *)DashBold7Glyphs,",
        f"                                    0x{first:02X}, 0x{last:02X}, {H + 2}}};", ""]
OUT.write_text("\n".join(out))
print(f"{OUT.relative_to(ROOT)}: {len(glyphs)} glyphs, {len(bitmap)} bytes")
