#!/usr/bin/env python3
"""Our settings page, stamped and gzipped the way Patternflow ships its own.

    python3 tools/console_page.py <patternflow sketch dir> <page.html> <out header>

Patternflow's firmware/toolchain/console_pages.py turns console/*.html into
PROGMEM headers: it stamps the chrome tag with the chrome's CRC, adds the
fallback window.PF, and gzips the result. Its page list is fixed, so rather
than editing it we import it and run the same functions on our page.
The header holds only the gzip bytes (that is all the device sends).

Also importable: stamped(sketch, html) gives the page exactly as the panel
serves it, for tools/mock_panel.py.
"""
import os
import sys


def tool(sketch):
    sys.path.insert(0, os.path.join(sketch, "..", "toolchain"))
    import console_pages as cp
    cp.set_sketch(sketch)
    return cp


def stamped(sketch, html):
    cp = tool(sketch)
    return cp.stamp(html, cp.chrome_crc(), cp.load_shim(), "dashboard")


def main(sketch, src, out):
    cp = tool(sketch)
    with open(src, encoding="utf-8") as f:
        body = stamped(sketch, f.read())
    block, gz_len = cp.gz_block("DASHBOARD_INDEX_HTML", "static const", cp.payload(body), "\n")
    with open(out, "w", encoding="utf-8", newline="") as f:
        f.write("// GENERATED by tools/console_page.py from dashboard.html: edit that.\n"
                "#pragma once\n#include <Arduino.h>\n\n" + block)
    print("page:     %d -> %d bytes gz" % (len(cp.payload(body)), gz_len))


if __name__ == "__main__":
    main(*sys.argv[1:4])
